### ISSUE TITLE
SSD Woes

### ISSUE THREAD

**Issue by ghost** [wern-apfel/OC-EFI-Zenbook-UX434-#1]
Are you using this with an Optane SSD? If so, how do you make it work?

**Comment by wern-apfel** [comment]
No Optane SSD, but it should work if you switch the BIOS from RAID to AHCI.

**Comment by ghost** [comment]
I tried this, it just kernel panics with an ionvme error

**Comment by ghost** [comment]
Does the whole SSD have to be blank for that to work? Like as in both the 512GB and the 32GB parts?

**Comment by ghost** [comment]
Right now I've got a 128gb SSD in the system with a working install but it's a lot smaller than would be optimal and to use windows I have to switch the ssds

**Comment by wern-apfel** [comment]
You can partition the SSD with Windows and install macOS on the second partition.

**Comment by ghost** [comment]
Again, I've tried this but the system kernel panics

**Comment by ghost** [comment]
I'll get a pic of the issue

**Comment by wern-apfel** [comment]
Have you disabled secure boot?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
I'm installing the optane right now to show the issue

**Comment by wern-apfel** [comment]
Is the NVMe Samsung OEM? they have a PM981 controller which is not supported by macOS

**Comment by ghost** [comment]
I'm not sure, it's branded as intel optane H10,  it's the SSD this came with

**Comment by ghost** [comment]
If it is an unsupported controller, do you have any clue on how I could maybe fix it?

**Comment by wern-apfel** [comment]
Replace the SSD. Is it the UX434-FAC?

**Comment by ghost** [comment]
I'll get a picture where it panics

**Comment by ghost** [comment]
> Replace the SSD. Is it the UX434-FAC?

Yes, I could replace the SSD but I don't have the money to do so. I have a 128gb Toshiba that I know works because I installed to it but it's a hassle to swap the drives when I want to use windows and it's a small drive to dualboot

**Comment by ghost** [comment]
My attempt now is going to be trying to make Opencore not look for the ssd

**Comment by ghost** [comment]
That worked! Using an ssdt to make it not find the optane allows it to boot, I will send the ssdt later as to allow anyone with the same issue to use this with their ux434fac

**Comment by wern-apfel** [comment]
Does it panic because of the ionvme kext? A friend of mine also has an Intel nvme and it works.

**Comment by ghost** [comment]
It was the optane, by using an ssdt to disable it, the system now works and I'm in the midst of a macOS install
